<?php

$GLOBALS['item_viewers']=array(
    'blocks'=>array(
        'title'=>'Blocks',
        'arg'=>'blocks',
        'template'=>'items_blocks.tpl.php'
    ),
    'nodes'=>array(
        'title'=>'Nodes',
        'arg'=>'nodes',
        'template'=>'items_nodes.tpl.php'
    ),
    'tabular'=>array(
        'title'=>'Table',
        'arg'=>'table',
        'template'=>'items_table.tpl.php'
    ),
    'cinema'=>array(
        'title'=>'Rotator',
        'arg'=>'rotator',
        'template'=>'items_cinema.tpl.php'
    ),
    'calendar'=>array(
        'title'=>'Calendar',
        'arg'=>'calendar',
        'template'=>'items_calendar.tpl.php'
    ),
    'mapped'=>array(
        'title'=>'Residue',
        'arg'=>'residue',
        'template'=>'items_map.tpl.php'
    ),
    'syndication'=>array(
        'title'=>'RSS',
        'arg'=>'syndicate',
        'template'=>'items_syndicate.tpl.php'
    ),
);

$GLOBALS['sortings']=array(
    'created'=>array(
        'title'=>'Date',
        //'arg'=>'blocks',
    ),
    'weight'=>array(
        'title'=>'Weight',
        //'arg'=>'weight',
    ),
    'rand'=>array(
        'title'=>'Random',
        //'arg'=>'random',
    ),
    'alpha'=>array(
        'title'=>'Title',
        //'arg'=>'',
    ),
);

?>